import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "./providers";
import { NavigationBar } from "@/components/nav-bar/NavigationBar";
import { fonts } from "./fonts";
import GenericFooter from "@/components/footers/GenericFooter";
import { Box } from "@chakra-ui/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={fonts.roboto_condensed.variable}>
      <body className={inter.className}>
        <Providers>
          <NavigationBar />
          <Box minH="100vh">
            {children}
          </Box>
          <GenericFooter />
        </Providers>
      </body>
    </html>
  );
}
